### ISSUE TITLE
Wrong url binary

### ISSUE THREAD

**Issue by xinro** [dominique-mueller/hugo-installer#50] opened 2022-09-17 20:00 UTC
Hi...

Thanks for this project in advance.
It seems like hugo changed the filename  for windows 64, So the download link became an error.
Can you update it?

once again, I thank you very much.

**Comment by itsdevdom** [comment] 2022-09-20 00:38
I can confirm, asset names have been changed with the latest version [`0.103.0`](https://github.com/gohugoio/hugo/releases/tag/v0.103.0). I'll take a look over the next couple of days, thanks for reporting!

**Comment by kevinjcharles** [comment] 2022-09-20 21:32
The shame issue appears to impact the newly introduced macOS universal binaries.

[Hugo Releases](https://github.com/gohugoio/hugo/releases)
https://github.com/gohugoio/hugo/releases/download/v0.103.1/hugo_0.103.1_darwin-universal.tar.gz

Hugo Installer Output
https://github.com/gohugoio/hugo/releases/download/v0.103.1/hugo_extended_0.103.1_macOS-universal.tar.gz

Thanks in advance.

**Comment by itsdevdom** [comment] 2022-09-20 21:41
Oh man, just fixed those a few days ago :D I guess I will take a look at all binaries, thanks for the hint!

**Comment by kevinjcharles** [comment] 2022-09-22 17:25
> Oh man, just fixed those a few days ago :D I guess I will take a look at all binaries, thanks for the hint!

Thanks again. It looks like the change occurred with version [v0.103.0](https://github.com/gohugoio/hugo/releases/tag/v0.103.0). The naming convention went from [hugo_extended_0.102.3_macOS-universal.tar.gz](https://github.com/gohugoio/hugo/releases/download/v0.102.3/hugo_extended_0.102.3_macOS-universal.tar.gz) to [hugo_extended_0.103.0_darwin-universal.tar.gz](https://github.com/gohugoio/hugo/releases/download/v0.103.0/hugo_extended_0.103.0_darwin-universal.tar.gz).

**Comment by itsdevdom** [comment] 2022-09-27 16:45
Binary names have been fixed with release **[4.0.1](https://github.com/dominique-mueller/hugo-installer/releases/tag/4.0.1)** Enjoy! :tada:

**Closed as completed by itsdevdom** 2022-09-27 16:45 UTC
Labels: type: compatibility
